
def AccountingSupplierParty(
                              AdditionalAccountID,
                              PartyName,
                              PhysicalLocationID,
                              PhysicalLocationCityName,
                              PhysicalLocationCountrySubentity,
                              PhysicalLocationCountrySubentityCode,
                              PhysicalLocationAddressLine,
                              CountryIdentificationCode,
                              CountryName,
                              RegistrationName,
                              ProviderID,
                              ProviderIDDV,
                              TaxLevelCode,
                              RegistrationAddressID,
                              RegistrationAddressCityName,
                              RegistrationAddressCountrySubentity,
                              RegistrationAddressCountrySubentityCode,
                              RegistrationAddressAddressLine,
                              RegistrationAddressCountryIdentificationCode,
                              RegistrationAddressCountryName,
                              TaxSchemeID,
                              TaxSchemeName,
                              Prefix,
                              MatriculaMercantil
                              ):
    return(
        f"""<cac:AccountingSupplierParty>
      <cbc:AdditionalAccountID>{AdditionalAccountID}</cbc:AdditionalAccountID>
      <cac:Party>
         <cac:PartyName>
            <cbc:Name>{PartyName}</cbc:Name>
         </cac:PartyName>
         <cac:PhysicalLocation>
            <cac:Address>
               <cbc:ID>{PhysicalLocationID}</cbc:ID>
               <cbc:CityName>{PhysicalLocationCityName}</cbc:CityName>
               <cbc:CountrySubentity>{PhysicalLocationCountrySubentity}</cbc:CountrySubentity>
               <cbc:CountrySubentityCode>{PhysicalLocationCountrySubentityCode}</cbc:CountrySubentityCode>
               <cac:AddressLine>
                  <cbc:Line>{PhysicalLocationAddressLine}</cbc:Line>
               </cac:AddressLine>
               <cac:Country>
                  <cbc:IdentificationCode>{CountryIdentificationCode}</cbc:IdentificationCode>
                  <cbc:Name languageID="es">{CountryName}</cbc:Name>
               </cac:Country>
            </cac:Address>
         </cac:PhysicalLocation>
         <cac:PartyTaxScheme>
            <cbc:RegistrationName>{RegistrationName}</cbc:RegistrationName>
            <cbc:CompanyID schemeAgencyID="195" schemeAgencyName="CO, DIAN (Dirección de Impuestos y Aduanas Nacionales)" schemeID="{ProviderIDDV}" schemeName="31">{ProviderID}</cbc:CompanyID>
            <cbc:TaxLevelCode listName="05">{TaxLevelCode}</cbc:TaxLevelCode>
            <cac:RegistrationAddress>
               <cbc:ID>{RegistrationAddressID}</cbc:ID>
               <cbc:CityName>{RegistrationAddressCityName}</cbc:CityName>
               <cbc:CountrySubentity>{RegistrationAddressCountrySubentity}</cbc:CountrySubentity>
               <cbc:CountrySubentityCode>{RegistrationAddressCountrySubentityCode}</cbc:CountrySubentityCode>
               <cac:AddressLine>
                  <cbc:Line>{RegistrationAddressAddressLine}</cbc:Line>
               </cac:AddressLine>
               <cac:Country>
                  <cbc:IdentificationCode>{RegistrationAddressCountryIdentificationCode}</cbc:IdentificationCode>
                  <cbc:Name languageID="es">{RegistrationAddressCountryName}</cbc:Name>
               </cac:Country>
            </cac:RegistrationAddress>
            <cac:TaxScheme>
               <cbc:ID>{TaxSchemeID}</cbc:ID>
               <cbc:Name>{TaxSchemeName}</cbc:Name>
            </cac:TaxScheme>
         </cac:PartyTaxScheme>
         <cac:PartyLegalEntity>
            <cbc:RegistrationName>{RegistrationName}</cbc:RegistrationName>
            <cbc:CompanyID schemeAgencyID="195" schemeAgencyName="CO, DIAN (Dirección de Impuestos y Aduanas Nacionales)" schemeID="{ProviderIDDV}" schemeName="31">{ProviderID}</cbc:CompanyID>
            <cac:CorporateRegistrationScheme>
               <cbc:ID>{Prefix}</cbc:ID>
               <cbc:Name>{MatriculaMercantil}</cbc:Name>
            </cac:CorporateRegistrationScheme>
         </cac:PartyLegalEntity>
      </cac:Party>
   </cac:AccountingSupplierParty>""")