
# name: Client3 - Build and deploy Python app to Azure Web App

# env:
#   AZURE_WEBAPP_NAME: Client3-back-${{github.ref_name}}-centralus  # set this to the name of your Azure Web App
#   PYTHON_VERSION: '3.13'              # set this to the Python version to use

# on:
#   push:
#     branches: [ "prod","uat" ]
#   workflow_dispatch:

# permissions:
#   contents: read

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python version
#         uses: actions/setup-python@v3.0.0
#         with:
#           python-version: ${{ env.PYTHON_VERSION }}

#       - name: Create and start virtual environment
#         run: |
#           python -m venv venv
#           source venv/bin/activate

#       - name: Install dependencies
#         run: pip install -r requirements.txt

#       # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

#       - name: Upload artifact for deployment jobs
#         uses: actions/upload-artifact@v4
#         with:
#           name: python-app
#           path: |
#             .
#             !venv/

#   deploy:
#     permissions:
#       contents: none
#       id-token: write
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: "${{github.ref_name}}"
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: python-app
#           path: .

#       - name: Azure CLI Login
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#       - name: 'Deploy to Azure Web App'
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: ${{ env.AZURE_WEBAPP_NAME }}




# This workflow will build a Python app and deploy it to an Azure Functions App on Linux when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure Functions app.
# For instructions see https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python?pivots=python-mode-configuration
#
# To configure this workflow:
# 1. Set up the following secrets in your repository:
#   - AZURE_FUNCTIONAPP_PUBLISH_PROFILE
# 2. Change env variables for your configuration.
#
# For more information on:
#   - GitHub Actions for Azure: https://github.com/Azure/Actions
#   - Azure Functions Action: https://github.com/Azure/functions-action
#   - Publish Profile: https://github.com/Azure/functions-action#using-publish-profile-as-deployment-credential-recommended
#   - Azure Service Principal for RBAC: https://github.com/Azure/functions-action#using-azure-service-principal-for-rbac-as-deployment-credential
#
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples/tree/master/FunctionApp

name: Client3 - Deploy Python project to Azure Function App

on:
  push:
    branches: [ "prod","uat" ]
  workflow_dispatch:
  
env:
  AZURE_FUNCTIONAPP_NAME: Client3-back-${{github.ref_name}}-centralus   # set this to your function app name on Azure
  PYTHON_VERSION: '3.13'                     # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  build:
    runs-on: ubuntu-latest #-- GitHub hosted runner: the list are :
    steps:                 #-- ubuntu, windows, macos
      - name: Checkout repository
        uses: actions/checkout@v4 #-- checkout the branch

      - name: Setup Python version
        uses: actions/setup-python@v1 #-- setup python on runner
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: | #-- 'run' is used to run commands on environment
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt #-- run the file of requirements

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment 
        run: zip release.zip ./* -r       #-- package the project

      - name: Upload artifact for deployment job 
        uses: actions/upload-artifact@v3 #-- upload the project to be deployed
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "${{github.ref_name}}"
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     
        
      - name: 'Deploy to Azure Functions' 
        uses: Azure/functions-action@v1 #-- connect to cloud and deploy
        id: deploy-to-function
        with:
          app-name: 'my-func-test'
          slot-name: 'Production'
          package: .
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}